hzClinic/hzClinic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from crm import views

urlpatterns = [
    path('hzhzhz/', admin.site.urls),
    path('', views.main_view, name='main'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('recording/', views.recording_view, name='recording'),
    path('recording/<str:date>', views.recording_view, name='recording'),
    path('updrecord/<int:pk>', views.updrecord_view, name='updrecord'),
    path('delrecord/<int:pk>', views.delrecord_view, name='delrecord'),
    path('timeline/', views.timeline_view, name='timeline'),
    path('timeline/<str:set_date>', views.timeline_view, name='timeline'),
    path('quests/', views.quests_view, name='quests'),
    path('quests/<int:state_id>', views.quests_view, name='quests'),
    path('quest/<int:ext_id>', views.quest_view, name='quest'),
    path('quest_hide/<int:ext_id>', views.quest_hide, name='quest_hide'),
    path('analyzes/', views.analyzes_view, name='analyzes'),
    path('control/', views.control_view, name='control'),
    path('medcard/<int:pk>', views.medcard_view, name='medcard'),
    path('export_tl/', views.export_tl_view, name='export_tl'),
    path('export_tl/<encrypt_dates>', views.export_tl_view, name='export_tl'),
    path('loadrec/', views.loadrec_view, name='loadrec'),
]

handler404 = views.page_not_found_view

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

hzClinic/crm/forms.py
import django.forms.widgets
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import NON_FIELD_ERRORS
from django.forms import NumberInput, HiddenInput, ModelForm, CheckboxSelectMultiple, DateInput, TextInput, Select, Textarea

from users.models import CustomUser

from crm.models import hzUserInfo, Candidate, MedCard, TypeOperations


class LoginForm(forms.Form):
    user_login = forms.CharField(label='', max_length=50)
    user_password = forms.CharField(label='', max_length=10, widget=forms.PasswordInput())

    user_login.widget.attrs.update({'class': 'input-material', 'placeholder': 'введите логин (79998887755)'})
    user_password.widget.attrs.update({'class': 'input-material', 'placeholder': 'введите пароль'})


class QuestForm(forms.Form):
    phone = forms.CharField(max_length=16, label='Номер телефона')
    FIO = forms.CharField(max_length=100, label='Ф.И.О.')
    DateOfB = forms.DateField(input_formats=['%d.%m.%Y', '%Y-%m-%d'], label='Дата рождения')
    AddressRow = forms.CharField(max_length=255, label='Адрес места жительства из анкеты')
    Address = forms.CharField(max_length=255, label='Адрес обработанный (будет использован в документах)')
    veSub = forms.CharField(max_length=100, label='Субъект (Республика/Край/Область)')
    veRn = forms.CharField(max_length=100, label='Район субъекта')
    veGor = forms.CharField(max_length=100, label='Город')
    veNP = forms.CharField(max_length=100, label='Населённый пункт')
    veUl = forms.CharField(max_length=100, label='Улица (без ул.)')
    veDom = forms.CharField(max_length=100, label='Номер дома')
    veStr = forms.CharField(max_length=100, label='Строение/Корпус/Владение и т.д.')
    veKv = forms.CharField(max_length=100, label='Квартира')
    PerZ = forms.CharField(max_length=100, label='Перенесённые и хронические заболевания?')
    PerO = forms.CharField(max_length=100, label='Перенесённые пластические операции')
    PerT = forms.CharField(max_length=100, label='Перенесённые травмы')
    PerG = forms.CharField(max_length=100, label='Перенесённые гемотрансфузии')
    Allerg = forms.CharField(max_length=100, label='Аллергии')
    VICH = forms.CharField(max_length=100, label='ВИЧ')
    Gepatit = forms.CharField(max_length=100, label='Гепатит')
    Tub = forms.CharField(max_length=100, label='Туберкулёз')
    Diabet = forms.CharField(max_length=100, label='Диабет')
    Vener = forms.CharField(max_length=100, label='Венерические заболевания')
    Alk = forms.CharField(max_length=100, label='Отношение к алкоголю')
    Kur = forms.CharField(max_length=100, label='Отношение к курению')
    Nark = forms.CharField(max_length=100, label='Отношение к наркотикам')
    MedPrep = forms.CharField(max_length=100, label='Лекарственные препараты на постоянной основе')
    MedIzd = forms.CharField(max_length=100, label='Медицинские изделия')
    Gender = forms.CharField(max_length=100, label='Пол')
    oGender = forms.CharField(max_length=100, label='Дополнительная информация для осмотра, в зависимости от пола')
    Rost = forms.CharField(max_length=100, label='Рост, см')
    Massa = forms.CharField(max_length=100, label='Вес, кг')
    GK = forms.CharField(max_length=100, label='Группа крови (O(I), A(II), B(III), AB(IV))')
    RH = forms.CharField(max_length=100, label='Резус-фактор (+, -)')
    KELL = forms.CharField(max_length=100, label='Келл-фактор (отрицательный, положительный)')

    # class Meta:
    #     # model = hzUserInfo
    #     # exclude = ['hz_user', 'type', ]
    #     widgets = {'AddressRow': forms.Textarea,
    #                #'reg_address': Textarea(),
    #                }


class CandidateForm(ModelForm):
    error_css_class = 'has-danger'
    # required_css_class = 'has-warning'

    class Meta:
        error_messages = {'typeOpers': {'required': 'Не выбраны виды планируемых операций!'},
                          'phoneNumber': {'unique': 'Кандидат с таким номером телефона уже записан!'}
                          }
        labels = {'typeOpers': 'Операции (обязательное*)', 'date_oper': 'Дата операции (обязательное*)',
                  'phoneNumber': 'Номер телефона (обязательное*)', 'Sname': 'Фамилия (обязательное*)',
                  'Name': 'Имя (обязательное*)', 'Mname': 'Отчество (необязательное)',
                  'notes': 'Примечания (необязательное)',
                  'Doctor': 'Оперирующий хирург (выберите из списка)',
                  }
        model = Candidate
        fields = ['date_oper', 'phoneNumber', 'Sname', 'Name', 'Mname', 'notes', 'typeOpers', 'Doctor', 'total_duration']
        widgets = {
            'typeOpers': CheckboxSelectMultiple(attrs={'class': 'form-control-label'}),
            'date_oper': TextInput(attrs={'type': 'date', 'class': 'form-control'}),
            'phoneNumber': TextInput(attrs={'placeholder': 'формат ввода 79998887766', 'class': 'form-control'}),
            'Sname': TextInput(attrs={'help_text': 'help_text', 'placeholder': 'Фамилия', 'class': 'form-control'}),
            'Name': TextInput(attrs={'placeholder': 'Имя', 'class': 'form-control'}),
            'Mname': TextInput(attrs={'placeholder': 'Отчество', 'class': 'form-control'}),
            'Doctor': Select(attrs={'placeholder': 'Хирург', 'class': 'form-control form-control-lg'}),
            'notes': Textarea(attrs={'placeholder': 'Примечания', 'class': 'form-control'}),
            'total_duration': NumberInput(attrs={'class': 'form-control'}),

        }


class MedCardForm(ModelForm):
    candidate = forms.ModelChoiceField(queryset=Candidate.objects.all().order_by('-date_oper'), label='Кандидат', widget=forms.Select(attrs={'class': 'form-control form-control-lg'}))

    class Meta:
        model = MedCard
        fields = "__all__"
        widgets = {
            'anket_id': TextInput(attrs={'class': 'form-control', 'readonly': ''}),
            'phone': TextInput(
                attrs={'placeholder': 'формат ввода 79998887766', 'class': 'form-control', 'readonly': ''}),
            'date_filling': TextInput(attrs={'type': 'date', 'class': 'form-control', 'readonly': ''}),
            'date_oper': TextInput(attrs={'type': 'date', 'class': 'form-control'}),
            's_name': TextInput(attrs={'placeholder': 'Фамилия', 'class': 'form-control'}),
            'name': TextInput(attrs={'placeholder': 'Имя', 'class': 'form-control'}),
            'm_name': TextInput(attrs={'placeholder': 'Отчество', 'class': 'form-control'}),
            'DateOfB': TextInput(attrs={'type': 'date', 'class': 'form-control'}),
            'AddressRow': TextInput(attrs={'class': 'form-control', 'readonly': ''}),
            'Address': TextInput(attrs={'class': 'form-control'}),
            'veSub': TextInput(attrs={'class': 'form-control'}),
            'veRn': TextInput(attrs={'class': 'form-control'}),
            'veGor': TextInput(attrs={'class': 'form-control'}),
            'veNP': TextInput(attrs={'class': 'form-control'}),
            'veUl': TextInput(attrs={'class': 'form-control'}),
            'veDom': TextInput(attrs={'class': 'form-control'}),
            'veStr': TextInput(attrs={'class': 'form-control'}),
            'veKv': TextInput(attrs={'class': 'form-control'}),
            'PerZ': TextInput(attrs={'class': 'form-control'}),
            'PerO': TextInput(attrs={'class': 'form-control'}),
            'PerT': TextInput(attrs={'class': 'form-control'}),
            'PerG': TextInput(attrs={'class': 'form-control'}),
            'Allerg': TextInput(attrs={'class': 'form-control'}),
            'VICH': TextInput(attrs={'class': 'form-control'}),
            'Gepatit': TextInput(attrs={'class': 'form-control'}),
            'Tub': TextInput(attrs={'class': 'form-control'}),
            'Diabet': TextInput(attrs={'class': 'form-control'}),
            'Vener': TextInput(attrs={'class': 'form-control'}),
            'Alk': TextInput(attrs={'class': 'form-control'}),
            'Kur': TextInput(attrs={'class': 'form-control'}),
            'Nark': TextInput(attrs={'class': 'form-control'}),
            'MedPrep': TextInput(attrs={'class': 'form-control'}),
            'MedIzd': TextInput(attrs={'class': 'form-control'}),
            'Gender': TextInput(attrs={'class': 'form-control'}),
            'oGender': TextInput(attrs={'class': 'form-control'}),
            'Rost': NumberInput(attrs={'class': 'form-control'}),
            'Massa': NumberInput(attrs={'class': 'form-control'}),
            'GK': Select(attrs={'class': 'form-control form-control-lg'}),
            'RH': Select(attrs={'class': 'form-control form-control-lg'}),
            'KELL': Select(attrs={'class': 'form-control form-control-lg'}),
            'typeOpers': CheckboxSelectMultiple(attrs={'class': 'form-control-label'}),
            'PZK': Select(attrs={'class': 'form-control form-control-lg'}),
            'anest': Select(attrs={'class': 'form-control form-control-lg'}),
            'schema': Select(attrs={'class': 'form-control form-control-lg'}),
            'surgeon': Select(attrs={'class': 'form-control form-control-lg'}),
            'candidate': Select(attrs={'class': 'form-control form-control-lg'}),
            'ya_folder': TextInput(attrs={'class': 'form-control', 'readonly': ''}),
        }
        labels = {'PZK': 'Состояние подкожно-жировой клетчатки', 'date_oper': 'Дата операции (обязательное*)',
                  'surgeon': 'Оперирующий хирург', 'typeOpers': 'Планируемые виды операций',
                  }


class UploadForm(forms.Form):
    data_file = forms.FileField(label='Выберите файл для загрузки')

hzClinic/crm/templates/crm/_content_export_tl.html
{% load static %}
<!-- Bootstrap CSS-->
<link rel="stylesheet" href={% static "crm/css/bootstrap.min.css" %}>
<link rel="stylesheet" href={% static "crm/css/font-awesome.min.css" %}>
<link rel="stylesheet" href={% static "crm/css/uikit.min.css" %}>
<link rel="stylesheet" href={% static "crm/fonts/Raleway.ttf" %}>
<script src={% static "crm/js/uikit.min.js" %}></script>
<script src={% static "crm/js/uikit-icons.min.js" %}></script>
<style>
    .body {
    font-family: 'Raleway';
    }
    .link-text {
  display: none;
}
</style>
<script type="text/javascript">
    function Copy(containerid) {
          let textarea = document.createElement('textarea');
          textarea.id = 'temp';
          textarea.style.height = 0;
          document.body.appendChild(textarea);
          textarea.value = document.getElementById(containerid).innerText;
          let selector = document.querySelector('#temp');
          selector.select();
          document.execCommand('copy');
          document.body.removeChild(textarea);
    }
</script>

<div class="col-lg-12">
    <div class="card">
        <div class="card-header d-flex align-items-center">
            Расписание операций с {{ start_date|date:"d.m.Y" }} г. по {{ end_date|date:"d.m.Y" }} г.
        </div>
        <div class="card-header d-flex align-items-center">
            <a href="{{ public_link }}">ссылка для просмотра расписания</a>   
            <a href="#" onclick="Copy('toCopy')" title="Копировать" class="text-primary" uk-icon="icon: copy; ratio: 1.5"></a>
            <p id="toCopy" class="link-text">https://hzcrm.hotyanznaet.ru/export_tl/{{ public_link }}</p>
        </div>
        <div class="card-body">
            <table class="table table-striped table-sm table-responsive">
                <thead>
                <tr>
                    <th>№ п.п.</th>
                    <th>Дата операции</th>
                    <th>Ф.И.О. пациента</th>
                    <th>Запланированные операции</th>
                    <th>Оперирующий хирург</th>
                    <th>Примечания</th>
                </tr>
                </thead>
                <tbody>
                {% for candidat in data %}
                <tr>
                    <td><input type="checkbox" value="">  {{ forloop.counter }}</td>
                    <td>{{ candidat.date_oper|date:"d.m.Y" }}<br>{{ candidat.date_oper|date:"l" }}</td>
                    <td>{{ candidat.Sname }} {{ candidat.Name }} {{ candidat.Mname }}<br>{{ candidat.phoneNumber }}</td>
                    <td>
                        <ul class="p-3">
                            {% for oper in candidat.typeOpers.all %}
                            <li>{{ oper.name }}</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ candidat.Doctor }}</td>
                    <td>{{ candidat.notes|linebreaks }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

hzClinic/crm/templates/crm/_content_quest.html
{% load static %}
<div class="content-inner">
          <!-- Page Header-->
          <header class="page-header">
            <div class="container-fluid">
              <h2 class="no-margin-bottom">Оформление пакета документов</h2>
            </div>
          </header>
          <section class="tables">
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-12">
                  <div class="card">
                    <div class="card-close">
                      <div class="dropdown">
                        <button type="button" id="closeCard" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="dropdown-toggle"><i class="fa fa-ellipsis-v"></i></button>
                        <div aria-labelledby="closeCard" class="dropdown-menu has-shadow"><a href="#" class="dropdown-item remove"> <i class="fa fa-times"></i>Close</a><a href="#" class="dropdown-item edit"> <i class="fa fa-gear"></i>Edit</a></div>
                      </div>
                    </div>
                    <div class="card-header d-flex align-items-center">
                      <h3 class="h4">Выбранная анкета</h3>

                    </div>
                    <div class="card-body">
                        <p>Данные отправленные пациентом, возможно редактирование.</p>
                      <table class="table table-striped table-sm">
                        <thead>
                          <tr>
                            <th>№ п.п.</th>
                            <th>Вопрос</th>
                            <th>Ответ</th>

                          </tr>
                        </thead>
                        <tbody>
                        {% if form %}
                         {% for item in form %}
                          <tr>
                            <th scope="row">{{forloop.counter}}</th>
                              <td>{{item.label}}</td>
                              <td><input id={{item.id_for_label}} value={{item.value}}></td>
<!--                              <td><a href="../quest/{{ item.external_id }}">{{ item.external_id }}</a></td>-->
<!--                              <td>{{ item.date_filling }}</td>-->
<!--                              <td>{{ item.FIO }}</td>-->
<!--                              <td>{{ item.DOB }}</td>-->
<!--                              <td>{{ item.tel }}</td>-->
<!--                              <td>{{ item.addr }}</td>-->
                          </tr>
                         {% endfor %}
                        {% endif %}
                        </tbody>
                      </table>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="card-body">
                            <table class="table table-striped table-sm">
                            {{ form.as_table }}
                            </table>
                            </div>
                            <input class="btn btn-primary" type="Submit" name="submit" value="Оформить"/>
                        </form>

                    </div>
                  </div>
                </div>
            </div>
            </div>
          </section>
          <!-- Page Footer-->
          <footer class="main-footer">
            <div class="container-fluid">
              <div class="row">
                <div class="col-sm-6">
                  <p>#ХотянЗнает! &copy; 2017-2022</p>
                </div>
                <div class="col-sm-6 text-right">
                  <p>Design by <a href="https://bootstrapious.com/admin-templates" class="external">Bootstrapious</a></p>
                </div>
              </div>
            </div>
          </footer>
        </div>

hzClinic/crm/templates/crm/_content_quest2.html
{% load static %}

<div class="content-inner">
    <!-- Page Header-->
    <header class="page-header">
        <div class="container-fluid">
            <h2 class="no-margin-bottom">Оформление документов для медицинской карты</h2>
        </div>
    </header>
    <ul class="breadcrumb">
        <div class="container-fluid">
            <li class="breadcrumb-item"><a href="../quests/0">Анкеты</a></li>
            <li class="breadcrumb-item active">{{ FIO }}</li>
        </div>
    </ul>
    <!-- Forms Section-->
    <section class="forms">
        <form action="/quest/{{ ext_id }}" method="post">
            <div class="container-fluid">
                <div class="row">
                    <!-- Anket Form-->
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header d-flex align-items-center">
                                <h3 class="h4">
                                    {% if state == 1 %}
                                    <div class="badge badge-rounded bg-red">документы уже оформлялись</div>
                                    {% endif %}
                                    Выбранная анкета № {{ ext_id }} от {{ date_filling|date:"d.m.Y" }} г.
                                </h3>
                                <input type="hidden" name="id_ext" value="{{ ext_id }}">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="badge-rounded bg-violet" style="text-align: center;">
                                    Данные отправленные пациентом. Необходима проверка.
                                </div>
                                {% csrf_token %}
                                {{ form.as_p }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                Правая панель
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header d-flex align-items-center">
                                <button type="button" data-toggle="modal" data-target="#myModal"
                                        class="btn btn-primary">Продолжить оформление
                                </button>
                            </div>
                        </div>
                    </div>
                    <!-- Modal-->
                    <div id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                         aria-hidden="true"
                         class="modal fade text-left">
                        <div role="document" class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 id="exampleModalLabel" class="modal-title">Подготовка
                                        документов для медицинской карты пациента <em>{{form.s_name.value}}
                                            {{form.name.value}} {{form.m_name.value}}</em>
                                    </h4>
                                    <button type="button" data-dismiss="modal" aria-label="Close"
                                            class="close"><span
                                            aria-hidden="true">×</span></button>
                                </div>
                                <div class="modal-body">
                                    <p>После оформления документы будут загружены в облачное
                                        хранилище.</p>
                                    <p>Дождитесь окончания процесса и возврата к списку анкет.</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" data-dismiss="modal"
                                            class="btn btn-secondary">Отмена
                                    </button>
                                    <input type="submit" class="btn btn-primary"
                                           value="Оформить документы">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </form>
    </section>
</div>

hzClinic/crm/templates/crm/_login.html
{%load static%}
<div class="page login-page">
    <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
            <div class="row">
                <!-- Logo & Information Panel-->
                <div class="col-lg-6">
                    <div class="info d-flex align-items-center">
                        <div class="content">
                            <div class="logo">
                                <h1>HZClinic</h1>
                            </div>
                            <p>CRM</p>
                        </div>
                    </div>
                </div>
                <!-- Form Panel    -->
                <div class="col-lg-6 bg-white">
                    <div class="form d-flex align-items-center">
                        <div class="content">
                            <div class="input-material">Введите логин и пароль</div>
                            <form id="LoginForm" method="post">
                                {%csrf_token%}
                                <!--                    <div class="form-group">-->
                                {{form}}
                                <!--                      <input id="login-username" type="text" name="loginUsername" required="" class="input-material">-->
                                <!--                      <label for="id_user_login" class="label-material">Логин</label>-->
                                <!--                    </div>-->
                                <!--                    <div class="form-group">-->
                                <!--                      <input id="login-password" type="password" name="loginPassword" required="" class="input-material">-->
                                <!--                      <label for="id_user_password" class="label-material">Пароль</label>-->
                                <!--                    </div><a id="login" href="CRM/main" class="btn btn-primary">Login</a>-->
                                <p></p>
                                <input class="btn btn-primary" type="submit" value="Вход">
                                <!--                    &lt;!&ndash; This should be submit button but I replaced it with <a> for demo purposes&ndash;&gt;-->
                            </form>
                            <!--                  <a href="#" class="forgot-pass">Забыли пароль?</a><br>-->
                            <!--                  <small>Ещё нет аккаунта? </small><a href="register.html" class="signup">Зарегистрируйтесь!</a>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="copyrights text-center">
    <p>Design by <a href="https://bootstrapious.com/admin-templates" class="external">Bootstrapious</a></p>
</div>

hzClinic/crm/templates/crm/_quest.html
{% extends "crm/_base.html" %}
{% load static %}
{% block LocalStyle %}
<style>
    ul {
     list-style-type: none; /* Убирает буллиты */
    }
</style>
{% endblock %}
{% block Content %}
{% include "crm/_content_medcard.html" %}
{% endblock %}

hzClinic/crm/templates/crm/_quests.html
{% extends "crm/_base.html" %}
{% load static %}
{% block Content %}
          {% include "crm/_content_quests.html" %}
{% endblock %}

hzClinic/crm/templates/crm/_record.html
{% extends "crm/_base.html" %}
{% load static %}
{% block LocalStyle %}
<style>
    ul {
     list-style-type: none; /* Убирает буллиты */
    }
</style>
{% endblock %}
{% block Content %}
          {% include "crm/_content_record.html" %}
{% endblock %}

hzClinic/crm/templates/crm/_sidebar_header.html
{% load static %}
<!-- Sidebar Header-->
<div class="sidebar-header d-flex align-items-center">
    <div class="avatar"><img src={{user_info.foto.url}} alt="..." class="img-fluid rounded-circle"></div>
    <div class="title">
        <h1 class="h4">{{user}}</h1>
<!--        <p>_hz_ {{type_lbl}}</p>-->
    </div>
</div>

hzClinic/crm/templates/crm/import.html
<!-- import.html -->
<form method="post" enctype="multipart/form-data" action="{% url 'loadrec' %}">
{% csrf_token %}
{{ form.as_p }}
<button type="submit">Импорт</button>
</form>

<!-- success.html -->
<p>Данные успешно импортированы.</p></html>

hzClinic/crm/templates/crm/main.html
<!DOCTYPE html>{% load static %}
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{{title}}{% endblock %}</title>
    <link rel="stylesheet" href={% static "crm/css/bootstrap.min.css" %}>
    <link rel="stylesheet" href={% static "crm/css/custom.css" %}>
</head>
<body class="" data-gr-c-s-loaded="true">


<main role="main">

    {% block hint %}
        {{main_body}}
    {% endblock %}
    <br>
    {% block content %}
     <div class="col-lg-6 bg-white">
       <div class="form-floating mb-3">
                <div class="form-floating mb-3">
                  <div class="input-material">Введите логин и пароль</div>
                  <form class="form-floating mb-3" id="QuestForm" method="post" >
                    {%csrf_token%}
<!--                    <div class="form-group">-->
                      <div class="mb-3">
                    {{form}}
                      </div>
<!--                      <input id="login-username" type="text" name="loginUsername" required="" class="input-material">-->
<!--                      <label for="id_user_login" class="label-material">Логин</label>-->
<!--                    </div>-->
<!--                    <div class="form-group">-->
<!--                      <input id="login-password" type="password" name="loginPassword" required="" class="input-material">-->
<!--                      <label for="id_user_password" class="label-material">Пароль</label>-->
<!--                    </div><a id="login" href="CRM/main" class="btn btn-primary">Login</a>-->
                    <p></p>
                    <input class="btn btn-primary" type="submit" value="Сохранить">
<!--                    &lt;!&ndash; This should be submit button but I replaced it with <a> for demo purposes&ndash;&gt;-->
                  </form>
<!--                  <a href="#" class="forgot-pass">Забыли пароль?</a><br>-->
<!--                  <small>Ещё нет аккаунта? </small><a href="register.html" class="signup">Зарегистрируйтесь!</a>-->
                </div>
              </div>
     </div>
    {% endblock %}
    {% block advice %}{% endblock %}
</main>

<hr>
{% block footer %}
<footer class="container">
    <p>© hzClinic 2020</p>
</footer>
{% endblock %}

<script src={% static "crm/js/jquery-3.3.1.slim.min.js" %}></script>
<script src={% static "crm/js/popper.min.js" %}></script>
<script src={% static "crm/js/bootstrap.min.js" %}></script>
</body>
</html>